### ISSUE TITLE
Can this call to WEB API then to MSGraph, or only can call directly to MSGraph

### ISSUE THREAD

**Issue by chauey** [MicrosoftDX/kurvejs#39]
If MSGraph does not have all the data we need, we want to add and have custom Planner Task data for example, how best to achieve login/CRUD/etc. for that (and Angular2)? Thanks!

**Comment by matvelloso** [comment]
Using AAD app model v1 you can register two apps, one for your web service and the other for your client web page. Then client web page requests an access token for your web service, calls your web service, then your web service uses that access token to request another one for the graph. It's what we call on behalf of tokens
