### ISSUE TITLE
graph.post using KurveJs is not working, Can you share a sample for that? 

### ISSUE THREAD

**Issue by ChetaPandya** [MicrosoftDX/kurvejs#40]

**Comment by billba** [comment]
Sorry, right now Kurve is read-only (no POST, PATCH, or DELETE support). I should clarify this in the documentation.

**Comment by matvelloso** [comment]
Hi,

Kurve JS is just an experimental library. It's not an official library and it hasn't been updated for quite a while. I'd recommend instead using the new MSAL library which is our official one for this: https://github.com/AzureAD/microsoft-authentication-library-for-js
